![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

In [230]:
import sys
import numpy as np

## Basic Numpy Arrays

In [231]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [232]:
a = np.array([1, 2, 3, 4])

In [233]:
b = np.array([0, .5, 1, 1.5, 2])

In [234]:
a[0], a[1]

(1, 2)

In [235]:
a[0:]

array([1, 2, 3, 4])

In [236]:
a[1:3]

array([2, 3])

In [237]:
a[1:-1]

array([2, 3])

In [238]:
a[::2]

array([1, 3])

In [239]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [240]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [241]:
# multindexing --> semelhante à célula acima
# multindexing retorna um np.array
b[[0, 2, -1]] 

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [242]:
a

array([1, 2, 3, 4])

In [243]:
a.dtype

dtype('int32')

In [244]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [245]:
b.dtype

dtype('float64')

In [246]:
np.array([1, 2, 3, 4], dtype=np.float16)

array([1., 2., 3., 4.], dtype=float16)

In [247]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [248]:
c = np.array(['a', 'b', 'c'])

In [249]:
c.dtype

dtype('<U1')

In [250]:
d = np.array([{'a': 1}, sys])

In [251]:
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [252]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [253]:
A.shape

(2, 3)

In [254]:
A.ndim

2

In [255]:
A.size

6

In [256]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [257]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [258]:
B.shape

(2, 2, 3)

In [259]:
B.ndim

3

In [260]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [261]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [262]:
A[1]

array([4, 5, 6])

In [263]:
A[1][0]

4

In [264]:
# A[d1, d2, d3, d4] --> multidimensional selection

# A[1, 0] == A[1][0]
A[1, 0]

4

In [265]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [266]:
# multdimensional selection também funciona com slicing

# A[:, :2]
# selecionar as linhas 0 até o final
# selecionar as colunas de 0 até o indice 2

A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [267]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [268]:
A[:2, 2:]

array([[3],
       [6]])

In [269]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [270]:
A[1] = np.array([10, 10, 10])

In [271]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [272]:
# A[2] = 99 == A[1] = np.array([99, 99, 99])

A[2] = 99

In [273]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [274]:
a = np.array([1, 2, 3, 4])

In [275]:
a.sum()

10

In [276]:
a.mean()

2.5

In [277]:
a.std()

1.118033988749895

In [278]:
a.var()

1.25

In [279]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [280]:
A.sum()

45

In [281]:
A.mean()

5.0

In [282]:
A.std()

2.581988897471611

In [283]:
A.sum(axis=0)

array([12, 15, 18])

In [284]:
A.sum(axis=1)

array([ 6, 15, 24])

In [285]:
A.mean(axis=0)

array([4., 5., 6.])

In [286]:
A.mean(axis=1)

array([2., 5., 8.])

In [287]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [288]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [289]:
a = np.arange(4)

In [290]:
a

array([0, 1, 2, 3])

In [291]:
# Vectorized operation --> A operação será aplicada a todos os elementos do array

a + 10

array([10, 11, 12, 13])

In [292]:
a * 10

array([ 0, 10, 20, 30])

In [293]:
a

array([0, 1, 2, 3])

In [294]:
a += 100

In [295]:
a

array([100, 101, 102, 103])

In [296]:
a = np.arange(4)

In [297]:
a

array([0, 1, 2, 3])

In [298]:
b = np.array([10, 10, 10, 10])

In [299]:
b

array([10, 10, 10, 10])

In [300]:
a + b

array([10, 11, 12, 13])

In [301]:
a * b

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [302]:
a = np.arange(4)

In [303]:
a

array([0, 1, 2, 3])

In [304]:
a[0], a[-1]

(0, 3)

In [305]:
a[[0, -1]]

array([0, 3])

In [306]:
# True se quiser selecionar o elemento, False se não quiser
a[[True, False, False, True]]

array([0, 3])

In [307]:
a

array([0, 1, 2, 3])

In [308]:
# Retorna um boolean array (mask) que satisfaz a condição a >= 2 para cada elemento do Array
a >= 2

array([False, False,  True,  True])

In [309]:
# Seleciona os elementos do array dada a mascara a >= 2
a[a >= 2]

array([2, 3])

In [310]:
a.mean()

1.5

In [311]:
a[a > a.mean()]

array([2, 3])

In [312]:
a[~(a > a.mean())]

array([0, 1])

In [313]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [314]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [315]:
A = np.random.randint(100, size=(3, 3))

In [316]:
A

array([[ 3,  5,  0],
       [75, 61, 58],
       [ 8, 23, 33]])

In [317]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([ 3,  0, 61,  8, 33])

In [318]:
A > 30

array([[False, False, False],
       [ True,  True,  True],
       [False, False,  True]])

In [319]:
A[A > 30]

array([75, 61, 58, 33])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [320]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [321]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [322]:
# Produto escalar
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [323]:
# Produto escalar
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [324]:
# Matriz transposta
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [325]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [326]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [327]:
# An integer in Python is > 28bytes
sys.getsizeof(1)

28

In [328]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [329]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [330]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [331]:
np.dtype(float).itemsize

8

### Lists are even larger

In [332]:
# A one-element list
sys.getsizeof([1])

64

In [333]:
# An array of one element in numpy
np.array([1]).nbytes

4

### And performance is also important

In [334]:
l = list(range(100000))

In [335]:
a = np.arange(100000)

In [336]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 1e+03 µs


216474736

In [337]:
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 5 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random` 

In [338]:
np.random.random(size=2)

array([0.64136569, 0.6034926 ])

In [339]:
np.random.normal(size=2)

array([ 1.2915101 , -2.18888989])

In [340]:
np.random.rand(2, 4)

array([[0.72920982, 0.91971328, 0.92585547, 0.02696536],
       [0.64387732, 0.00331674, 0.16390705, 0.22911954]])

---
### `arange`

In [341]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [342]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [343]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [344]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [345]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [346]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [347]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [348]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

In [349]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [350]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [351]:
np.zeros((3, 3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [352]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [353]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [354]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [355]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [356]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [357]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [358]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [359]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [360]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [361]:
"Hello World"[6]

'W'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)